export const CONFIG = {
  // World
  WORLD_WIDTH: 256,
  WORLD_HEIGHT: 256,
  CHUNK_SIZE: 16,
  TILE_SIZE: 16,
  RENDER_SCALE: 3,

  // Simulation
  TICKS_PER_SECOND: 20,
  MAX_NPCS: 200,
  INITIAL_NPC_COUNT: 12,

  // AI
  BRAIN_HIDDEN_SIZE: 64,
  REPLAY_BUFFER_SIZE: 1000,
  TRAINING_BATCH_SIZE: 32,
  TRAINING_INTERVAL_TICKS: 100,
  LEARNING_RATE: 0.001,
  DISCOUNT_FACTOR: 0.99,
  MUTATION_RATE: 0.05,

  // Needs
  HUNGER_DECAY: 0.0008,
  THIRST_DECAY: 0.0012,
  ENERGY_DECAY: 0.0005,
  WARMTH_DECAY: 0.0003,
  SOCIAL_DECAY: 0.0002,

  // Time
  TICKS_PER_HOUR: 100,
  HOURS_PER_DAY: 24,
  DAYS_PER_SEASON: 28,
  SEASONS_PER_YEAR: 4,

  // Rendering
  MAX_PARTICLES: 500,
  CAMERA_ZOOM_MIN: 1,
  CAMERA_ZOOM_MAX: 6,

  // Data
  LOG_LEVEL: 'standard' as 'minimal' | 'standard' | 'full',
  MAX_MEMORIES_PER_NPC: 200,
  MEMORY_CONSOLIDATION_INTERVAL: 500,
};
